================================================================================
Welcome to MarkUs (formerly known as OLM on Rails)
================================================================================

MarkUs (pronounced "mark us") is an open-source tool which recreates the ease
and flexibility of grading assignments with pen on paper, within a web
application.  It also allows students and instructors to form groups, and
collaborate on assignments. It's predecessor OLM (Online Marking) was
[[originally written|https://stanley.cdf.toronto.edu/drproject/csc49x/olm]]
in Python on top of the TurboGears framework.

The MarkUs project is a re-implementation of the Online Marking system using
Ruby on Rails. The goal of this project is to take what we learned from OLM
and our forays into [[Web-CAT|http://web-cat.cs.vt.edu/]], and build a
web-based marking tool that includes an early submission and testing system in
support of test driven development.


Project Resources
================================================================================

  * **Project Website** http://www.markusproject.org
  * **Developer's Blog** http://blog.markusproject.org
  * **Review Board** http://review.markusproject.org
  * **IRC Channel:** Our channel is #markus on irc.freenode.net.
    [[Logs of the channel|http://www.markusproject.org/irc/]] are also available.
  * **Sandbox** http://www.markusproject.org/admin-demo/
  * **User Guide:** [[MarkUs Documentation | UserGuide]]

.. todo Modify User Guide link

Screencasts
--------------------------------------------------------------------------------

 * [[Student File Submission: September 2 2009 |
   http://www.youtube.com/watch?v=ofpyaty20FQ]]
 * [[Student Group Formation: August 17, 2009 |
   http://www.youtube.com/watch?v=Ed_z_tHCAg8]]
 * [[The Grader View: June 6, 2009 |
   http://www.cs.toronto.edu/~reid/screencasts/OLM-2009-06-03.swf]]
 * [[Flexible Marking Scheme Selection: December 1, 2009 |
   http://www.youtube.com/watch?v=x4mbE3WBgog]]
 * [[Flexible Marking Scheme Criterion: December 1, 2009 |
   http://www.youtube.com/watch?v=tVkti9y91RA]]
 * [[Notes created through the Modal dialog as an Admin: December 3, 2009 |
   http://www.youtube.com/watch?v=eoxriy2cYW0]]
 * [[Notes created through the Modal dialog as a TA: December 3, 2009 |
   http://www.youtube.com/watch?v=J4r18LNDwPs]]
 * [[Creating and editing a grade entry form as an admin: December 4, 2009 |
   http://www.youtube.com/watch?v=r7UnaNYe2rw]]
 * [[Notes tab: December 11, 2009 |
 * http://www.youtube.com/watch?v=IcuG6AlJfvQ]]
 * [[Entering and releasing the marks for a grade entry form as an admin: April
   4, 2010 | http://www.youtube.com/watch?v=-v6eVy94pdI]]

MarkUs Developer Installation Guides
================================================================================
Linux
--------------------------------------------------------------------------------
  * [[Setting up a development environment on GNU/Linux|InstallationGnuLinux]]
    (i.e. Debian based systems) including Ruby on Rails, MarkUs and **Radrails
    IDE** (Eclipse plug-in)

Mac OS X
--------------------------------------------------------------------------------
  * [[Setting up a development environment on Mac OS X 10.6 (Snow Leopard) |
    InstallationMacOsX]]

Windows (Note: Linux and Mac OS X development environments generally caused less problems)
------------------------------------------------------------------------------------------------------------------------
  * [[Setting up a development environment on Windows using
    InstantRails | InstallationWindows]]

MarkUs Developer Documentation
================================================================================

Project Vitals
--------------------------------------------------------------------------------

Subversion repository: `svn co` ${RepositoryUrl}`/`

Mailing list address: [markus-dev@cs.toronto.edu](mailto:markus-dev@cs.toronto.edu)

Mailing [list archive at marc.info](http://marc.info/?l=markus-dev&r=1&w=2)

Project Members
--------------------------------------------------------------------------------

.. TODO Add manually the projects members

Term Work
--------------------------------------------------------------------------------

* __Fall 2010__

      * [Who is doing what? (punchlines/minutes)](http://blog.markusproject.org/?p=1713)

* __Summer 2010__

      * [Goals for Summer 2010](wiki:GoalsMay2010)

* __Winter 2010__

      * [Who is doing what? (punchlines/minutes)](http://blog.markusproject.org/?p=1049)

* __Fall 2009__

      * [Who is in charge of what, administratively?](http://blog.markusproject.org/?p=504)
      * [September 18 - Pre-meeting Status](http://blog.markusproject.org/?p=296)
      * [September 11 - Pre-meeting Status](wiki:PreMeetingStatusSept1109)

* __Summer 2009__

      * Have a look at our [Blog](http://blog.markusproject.org)!

* __Winter 2009__ (Meeting Notes)

       * [Jan 09: Introductions](wiki:MeetingJan09)
       * [Jan 16: Useful rails plugins](wiki:MeetingJan16)

Everything a Developer Needs to Know about Ruby, Ruby on Rails and MarkUs
--------------------------------------------------------------------------------

* __Getting Started with Ruby, Ruby on Rails and MarkUs__

    * [Documentation MarkUs Tag Cloud](https://stanley.cdf.toronto.edu/drproject/csc49x/olm_rails/tagcloud)
    * [Short Rails Debugging HOWTO](wiki:RailsDebugging)
    * [How to program in Ruby, Rubybook](http://www.rubycentral.com/pickaxe)
    * [Rails API](http://api.rubyonrails.org)
    * [Rails Guides](http://guides.rubyonrails.org)
    * [Using metric_fu](wiki:MetricFu)
    * [General Guide Lines to code - Code review from Mike Gunderloy](wiki:GeneralGuideLines)
    * <http://apidock.com/rails>
    * [Some notes from a Ruby book taken by Tara Clark](http://taraclark.wordpress.com/category/ruby-on-rails)
    * [How to run Selenium tests](wiki:SeleniumTesting)
    * [Acceptance/Cucumber tests](wiki:CucumberTesting)
    * [How to use the MarkUs API](wiki:ApiHowTo)
    * [How to use MarkUs Testing Framework](wiki:TestingFramework) (still in alpha)


* __MarkUs Coding Style/Coding Practices/Rails Gotchas__

    * [Basic Guidelines for MarkUs Development](wiki:DeveloperGuidelines)(**IMPORTANT!**)
    * [How to use Review Board](wiki:HowToReviewBoard)
    * [Rails erb quirks](wiki:RailsERbStyle)
    * [Use h (alias for html_escape) and sanitize in views](wiki:RailsViewsConventions)
    * **Please document your code according to the RDoc specification** (see [how to use RDOC](http://rdoc.sourceforge.net/doc/))
    * **Ruby compatibility:** Please check ticket: #206. Also check out the [difference between COUNT, LENGTH, and SIZE](http://blog.hasmanythrough.com/2008/2/27/count-length-size)
    * [Our Ruby/Rails testing guidelines](wiki:TestingGuidelines)
    * [Security testing guidelines](wiki:SecurityTesting)
    * [Internationalisation](wiki:Internationalization)

* __MarkUs API/Test Coverage__

    * [MarkUs Ruby Doc](http://www.markusproject.org/dev/app_doc)
    * [MarkUs Test Coverage](http://www.markusproject.org/dev/test_coverage)

* __MarkUs Releases__

    * [Preparing a Release and Patch](wiki:Preparing_Release_And_Patch)

* __User Roles and Stories for MarkUs__

    * General / Constraints

        * [[MarkUs is internationalized|GeneralUseCase_Internationalized]]
        * [[MarkUs is configurable|GeneralUseCase_Configurable]]
        * [[Rubrics are not allowed to change once Submissions have been
collected|GeneralUseCase_NoRubricChangesAfterCollection]]

    * [[Instructor|Role_Instructor]]

        * [[Instructors can create / edit assignments|Instructor_CreateEditAssignments]]
        * [[Instructors can download/export files|Instructor_DownloadExportFiles]]
        * [[Instructors can hide students|Instructor_HideStudents]]
        * [[Instructors can do everything that Graders can do|Instructor_CanDoWhatGradersDo]]
        * [[Instructors can release/unrelease completed marking results|Instructor_ReleaseMarkingResults]]
        * [[Instructors can map particular students/groups to Grader_(s) for marking|Instructor_MapGradersToGroupings]]
        * [[Instructors can download / export a file that describes the Student_/Grouping mapping to Graders|Instructor_DownloadMapGradersToGroupings]]
        * [[Instructors can upload a file that will do the Student_/Grouping mapping to Graders|Instructor_UploadMapGradersToGroupings]]
        * [[Instructors can manage groups without restrictions|Instructor_ManageGroupsWithoutRestrictions]]

    * [[Grader|Role_Grader]]

        * [[Graders can easily tell which submissions are assigned to them to mark|Grader_EasyToSeeWhatToMark]]
        * [[Graders can view a Submission from a Student_ / Grouping|Grader_ViewSubmissions]]
        * [[Graders can view/annotate/mark a particular file from a Submission|Grader_ViewAnnotateMarkParticularFile]]
        * [[Graders can add annotations to particular lines of code within a Submission File|Grader_AnnotateLinesOfCode]]
        * [[Graders can create reusable Annotations|Grader_CreateReusableAnnotations]]
        * [[Graders can create short, formatted overall comments on a Submission|Grader_CreateOverallComment]]
        * [[Graders can view and use a Rubric for marking a Submission for an Assignment|Grader_ViewUseRubric]]
        * [[Graders can view a summary of marked submissions|Grader_ViewSummaryOfMarkedSubmissions]]
        * [[Graders can add bonuses / penalties to submissions|Grader_AddBonusesPenalties]]
        * [[Graders can modify the marking state of a submission result|Grader_CanModifyMarkingStatus]]
        * [[Graders can easily switch to the next / previous Submission for marking|Grader_CanSwitchToNextSubmission]]

    * [[Student|Role_Student]]

        * [[Students can view marks of submissions|Student_ViewMarks]]
        * [[Students can view annotations of marked submissions/assignments|Student_ViewAnnotations]]
        * [[Students can submit files for their assignments|Student_SubmitFiles]]
        * [[Students can view/edit submission files for assignments|Student_ViewEditFiles]]

* __Database Schema__

    * [AutoGenerate Database Schema|auto_generate_schema_diagram)
    * [View Schema Diagram](wiki:schema_diagram)
    * [Questions and Answers (Old Document)](wiki:Schema_Questions)

* __MarkUs Component Descriptions__

    * [File Persistence Layer](wiki:File_Persistence_Layer)
    * [Group / Grouping Behaviours](wiki:Groups_Grouping)
    * [Groupings and Repositories](wiki:GroupsGroupingsRepositories)
    * [Authentication and Authorization](wiki:Authentication)
    * [Annotations](wiki:Annotations)
    * [Instructor, TA, and Student Use Cases; TA to Groups Mapping; Users](wiki:VeronicaDocumentation)
    * [Rubrics and Grading](wiki:RubricsAndGrading)
    * [How Student Work is Graded](wiki:How_Grading_Works)
    * [Submission Rules](wiki:Submission_Rules)
    * [The FilterTable Class](wiki:FilterTable)
    * [Simple Grade Entry](wiki:SimpleGradeEntry)
    * [Notes System](wiki:NotesSystem)

* __Quicklinks for Browsing User Stories__

    * [Constraint Stories](https://stanley.cdf.toronto.edu/drproject/csc49x/olm_rails/tagcloud/tagsearch?perproject=True&q=UserStories+Constraints)
    * [Role Stories](https://stanley.cdf.toronto.edu/drproject/csc49x/olm_rails/tagcloud/tagsearch?perproject=True&q=UserStories+Roles)
    * [User Stories, excluding Roles/Constraints](https://stanley.cdf.toronto.edu/drproject/csc49x/olm_rails/tagcloud/tagsearch?perproject=True&q=UserStories+Stories)
    * [User Stories, Students Role](https://stanley.cdf.toronto.edu/drproject/csc49x/olm_rails/tagcloud/tagsearch?perproject=True&q=UserStories+Stories+StudentsRole)
    * [User Stories, TAs Role](https://stanley.cdf.toronto.edu/drproject/csc49x/olm_rails/tagcloud/tagsearch?perproject=True&q=UserStories+Stories+TAsRole)
    * [User Stories, Instructors Role](https://stanley.cdf.toronto.edu/drproject/csc49x/olm_rails/tagcloud/tagsearch?perproject=True&q=UserStories+Stories+InstructorsRole)
    * [Show all Stories, excluding Tickets](https://stanley.cdf.toronto.edu/drproject/csc49x/olm_rails/tagcloud/tagsearch?perproject=True&q=UserStories)


* __Feedback Notes__

    * [2009-05-22: Phyliss](wiki:PhylissFeedback)
    * [2009-06-22: Ryan](wiki:RyanFeedback)

* __Tips and Tricks__

    * [Dropping/Rebuilding Database Quickly and Easily](wiki:DropAndRebuildDb)

* __IDE/Editor Notes__

    * [jEdit](wiki:JEdit)
    * [NetBeans](wiki:NetBeans)

* __Other__

    * [MarkUs and Subversion compilation proceedings (RHEL, on markusproject.org)](wiki:CompileSVN)
    * [Load-testing a deployed MarkUs installation](wiki:LoadTesting)

* [MarkUs Feature Requests](https://stanley.cdf.toronto.edu/drproject/csc49x/olm_rails/tagcloud/tagsearch?perproject=True&q=FeatureRequest)

---------

MarkUs Deployment Documents (Installation Instructions for MarkUs using RAILS_ENV=production)
===============================================================================================

  * [Setup Instructions for MarkUs "Stable"](wiki:InstallProdStable)
  * [Hosting several MarkUs applications on one machine (for Production)](wiki:MultipleHosting)
  * [How to use LDAP with MarkUs](wiki:LDAP)
  * [How to use Phusion Passenger instead of Mongrel](wiki:Passenger)
  * *Old deployment instructions*:
    * Deploying and Configuring MarkUs for Production. [Instructions MarkUs version 0.5.](wiki:InstallProd). [Instructions MarkUs version 0.6.](wiki:InstallProd_0.6). 

---------

# DrProject info

*  [[DrProjectGuide]] --  Built-in Documentation
*  [The DrProject Project](https://www.drproject.org/DrProject)

For a complete list of local wiki pages, see [[TitleIndex]].
