MarkUs' Issue Labels: What They Mean
=============================

Unfortunately, the ordering of issues (which should represent priorities on Github) doesn't quite work. That's why a new set of labels has been added to suit our needs. Their meaning is as follows:

 * RFE: Request for enhancement (Feature Request)
 * Bug: Self explanatory
 * ✘'s (red) are for bug prioritization (there are 6 ✘'s, 3 ✘'s and 1 ✘; the higher the number of ✘'s the higher the priority)
 * Checkmarks (green; ✔) are for RFE prioritization. Scheme is similar to bug prioritization. The more checkmarks the higher the desire to get this implemented.
 * Various 'x.y.z' labels where x is the major release number, y minor, z micro. Those labels should merely be for release planning. For example all bugs which should be fixed by 0.9.3 have that label.
 * ECN: Ecole Centrale Nante. Can be used to filter for ECN specific things.
 * UW: University of Waterloo. Can be used to mark UW specific things.
 * UT: University of Toronto. Same thing.
 * REJECTED: Rejected issues.