Steps may be something along those lines
===============================

1. Make sure app/MARKUS_VERSION is updated

2. Make sure Changelog gets updated.

3. Make sure a tag gets created for the according release
4. Make sure a branch for the minor version number (0.7.x for 0.7.0) gets created and pushed
5. Prepare the archive (see below)
6. Prepare a patch for micro release updates.
7. Upload patch and archive
8. Update latest-stable symlink in /download directory on markusproject.org
9. Update index.html on markusproject.org and release note (blog.markusproject.org)


Prepare the tar archive from the Git tree
=============================

```sh
  $ git checkout <branchname>
  $ git log
  $ git archive --format=tar -o markus-<version-number> --prefix=markus-<version-number>/ refs/tags/<markus-version-number>
```

Prepare a patch from Git
==================

```sh
  $ git diff refs/tags/<markus-version> refs/tags/<markus-version> > markus-<markus-version>.patch
```
